# -*- coding: utf-8 -*-
"""pythonFirst.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WUbpVdZGrzInDxmYRe1EtZBpyfjUPDvC
"""

print("Labas");

1+2

list = [1, 2]

list[0]

sum([1, 2])

listas = [1, 2, 3, 4]
sum(listas)

def sumos_funkcija_plius_du(a, b):
  return a+b+2

sumos_funkcija_plius_du(1, 2)

sumos_funkcija_plius_du(5, 10)

#komentaras sau, nevykdomas

#isoriniai paketai-libraries

import numpy

numpy.sum(listas)

import pandas

lentele = pandas.read_csv('sample_data/california_housing_test.csv')

lentele

lentele.mean()

lentele.min()

lentele['total_bedrooms'].plot()

lentele.head(4)

import seaborn
x = lentele['households']
y = lentele['population']
seaborn.scatterplot(x, y)

lentele.corr()

koreliacijos = lentele.corr()
seaborn.heatmap(koreliacijos, annot=True)